#
# Makefile for kernel LTE data driver with SDMA support
#

obj-y := lte_dd.o
EXTRA_CFLAGS := $(HOST_PLATFORM_CFLAGS) -Idrivers/lte/include -Idrivers/lte/common/ -Iinclude/
lte_dd-objs := lte_data_driver_main_sdma.o lte_data_driver_cmds.o
#../common/ptr_fifo.o ../common/time_calc.o



