#ifndef __ARCH_ARM_MACH_OMAP2_CM_REGBITS_W3G_H
#define __ARCH_ARM_MACH_OMAP2_CM_REGBITS_W3G_H

/*
 * OMAPW3G Clock Management register bits
 *
 * Copyright (C) 2007-2008 Texas Instruments, Inc.
 * Copyright (C) 2007-2008 Nokia Corporation
 *
 * Written by Paul Walmsley
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include "cm.h"

/* Bits specific to each register */

/* CM_CLKTRCTRL Values */
#define OMAPW3G_CLKSTCTRL_DISABLE_AUTO         0x0
#define OMAPW3G_CLKSTCTRL_FORCE_SLEEP          0x1
#define OMAPW3G_CLKSTCTRL_FORCE_WAKEUP         0x2
#define OMAPW3G_CLKSTCTRL_ENABLE_AUTO          0x3


/* CM_REVISION specific bits */

/* CM_SYSCONFIG specific bits */

/* CM_CLKEN_PLL_MPU */
#define OMAPW3G_MPU_DPLL_DITH_TYPE_SHIFT                15
#define OMAPW3G_MPU_DPLL_DITH_TYPE_MASK			(1 << 15)
#define OMAPW3G_MPU_DPLL_DITH_SPREAD_SHIFT              13
#define OMAPW3G_MPU_DPLL_DITH_SPREAD_MASK		(0x3 << 13)
#define OMAPW3G_MPU_DPLL_DITH_FREQ_SHIFT		11
#define OMAPW3G_MPU_DPLL_DITH_FREQ_MASK			(0x3 << 11)
#define OMAPW3G_MPU_DPLL_DITH_EN_SHIFT                  10
#define OMAPW3G_MPU_DPLL_DITH_EN_MASK			(1 << 10)
#define OMAPW3G_MPU_DPLL_RAMPTIME_SHIFT			8
#define OMAPW3G_MPU_DPLL_RAMPTIME_MASK			(0x3 << 8)
#define OMAPW3G_MPU_DPLL_FREQSEL_SHIFT			4
#define OMAPW3G_MPU_DPLL_FREQSEL_MASK			(0xf << 4)
#define OMAPW3G_EN_MPU_DPLL_DRIFTGUARD_SHIFT		3
#define OMAPW3G_EN_MPU_DPLL_DRIFTGUARD_MASK		(1 << 3)
#define OMAPW3G_EN_MPU_DPLL_SHIFT			0
#define OMAPW3G_EN_MPU_DPLL_MASK			(0x7 << 0)

/* CM_IDLEST_MPU */
#define OMAPW3G_ST_MPU					(1 << 0)

/* CM_IDLEST_PLL_MPU */
#define OMAPW3G_ST_MPU_DITH_ACK_SHIFT			8
#define OMAPW3G_ST_MPU_DITH_ACK_MASK			(1 << 8)
#define OMAPW3G_ST_MPU_CLK_SHIFT			0
#define OMAPW3G_ST_MPU_CLK_MASK				(1 << 0)

/* CM_AUTOIDLE_PLL_MPU */
#define OMAPW3G_AUTO_MPU_DPLL_SHIFT			0
#define OMAPW3G_AUTO_MPU_DPLL_MASK			(0x7 << 0)

/* CM_CLKSEL1_PLL_MPU */
#define OMAPW3G_MPU_CLK_SRC_SHIFT			19
#define OMAPW3G_MPU_CLK_SRC_MASK			(0x3 << 19)
#define OMAPW3G_MPU_DPLL_MULT_SHIFT			8
#define OMAPW3G_MPU_DPLL_MULT_MASK			(0x7ff << 8)
#define OMAPW3G_MPU_DPLL_DIV_SHIFT			0
#define OMAPW3G_MPU_DPLL_DIV_MASK			(0x7f << 0)

/* CM_CLKSEL2_PLL_MPU */
#define OMAPW3G_MPU_DPLL_CLKOUT_DIV_SHIFT		0
#define OMAPW3G_MPU_DPLL_CLKOUT_DIV_MASK		(0x1f << 0)

/* CM_CLKSTCTRL_MPU */
#define OMAPW3G_CLKTRCTRL_MPU_SHIFT			0
#define OMAPW3G_CLKTRCTRL_MPU_MASK			(0x3 << 0)

/* CM_CLKSTST_MPU */
#define OMAPW3G_CLKACTIVITY_MPU_SHIFT			0
#define OMAPW3G_CLKACTIVITY_MPU_MASK			(1 << 0)

/* CM_FCLKEN_CORE specific bits */
#define OMAPW3G_EN_USIMOCP_32K				(1 << 14)
#define OMAPW3G_EN_USIMOCP_32K_SHIFT			14
#define OMAPW3G_EN_I2C_FCLKEN				(1 << 13)
#define OMAPW3G_EN_I2C_FCLKEN_SHIFT			13

/* CM_ICLKEN_CORE specific bits */
#define OMAPW3G_EN_DBG					(1 << 20)
#define OMAPW3G_EN_DBG_SHIFT				20
#define OMAPW3G_EN_ELM					(1 << 17)
#define OMAPW3G_EN_ELM_SHIFT				17
#define OMAPW3G_EN_MODEM_CIPHER				(1 << 15)
#define OMAPW3G_EN_MODEM_CIPHER_SHIFT			15
#define OMAPW3G_EN_MAD2D				(1 << 14)
#define OMAPW3G_EN_MAD2D_SHIFT				14
#define OMAPW3G_EN_CTRL					(1 << 13)
#define OMAPW3G_EN_CTRL_SHIFT				13
#define OMAPW3G_EN_I2C_ICLKEN				(1 << 12)
#define OMAPW3G_EN_I2C_ICLKEN_SHIFT			12
#define OMAPW3G_EN_SDRC					(1 << 7)
#define OMAPW3G_EN_SDRC_SHIFT				7

/* CM_IDLEST_CORE specific bits */
#define OMAPW3G_ST_DBG					(1 << 20)
#define OMAPW3G_ST_DBG_SHIFT				20
#define OMAPW3G_ST_ELM					(1 << 17)
#define OMAPW3G_ST_ELM_SHIFT				17
#define OMAPW3G_ST_MDMA					(1 << 16)
#define OMAPW3G_ST_MDMA_SHIFT				16
#define OMAPW3G_ST_MODEM_CIPHER				(1 << 15)
#define OMAPW3G_ST_MODEM_CIPHER_SHIFT			15
#define OMAPW3G_ST_MAD2D				(1 << 14)
#define OMAPW3G_ST_MAD2D_SHIFT				14
#define OMAPW3G_ST_CTRL					(1 << 13)
#define OMAPW3G_ST_CTRL_SHIFT				13
#define OMAPW3G_ST_SDRC					(1 << 7)
#define OMAPW3G_ST_SDRC_SHIFT				7

/* CM_AUTOIDLE_CORE */
#define OMAPW3G_AUTO_DBG				(1 << 20)
#define OMAPW3G_AUTO_DBG_SHIFT				20
#define OMAPW3G_AUTO_RCI				(1 << 19)
#define OMAPW3G_AUTO_RCI_SHIFT				19
#define OMAPW3G_AUTO_SDIOSLAVE				(1 << 18)
#define OMAPW3G_AUTO_SDIOSLAVE_SHIFT			18
#define OMAPW3G_AUTO_ELM				(1 << 17)
#define OMAPW3G_AUTO_ELM_SHIFT				17
#define OMAPW3G_AUTO_MODEM_CIPHER			(1 << 15)
#define OMAPW3G_AUTO_MODEM_CIPHER_SHIFT			15
#define OMAPW3G_AUTO_MAD2D				(1 << 14)
#define OMAPW3G_AUTO_MAD2D_SHIFT			14
#define OMAPW3G_AUTO_CTRL				(1 << 13)
#define OMAPW3G_AUTO_CTRL_SHIFT				13
#define OMAPW3G_AUTO_I2C				(1 << 12)
#define OMAPW3G_AUTO_I2C_SHIFT				12
#define OMAPW3G_AUTO_2GL1T				(1 << 11)
#define OMAPW3G_AUTO_2GL1T_SHIFT			11
#define OMAPW3G_AUTO_USIMOCP				(1 << 10)
#define OMAPW3G_AUTO_USIMOCP_SHIFT			10
#define OMAPW3G_AUTO_MMCSD2				(1 << 9)
#define OMAPW3G_AUTO_MMCSD2_SHIFT			9
#define OMAPW3G_AUTO_MMCSD1				(1 << 8)
#define OMAPW3G_AUTO_MMCSD1_SHIFT			8
#define OMAPW3G_AUTO_SDRC				(1 << 7)
#define OMAPW3G_AUTO_SDRC_SHIFT				7
#define OMAPW3G_AUTO_SPI1				(1 << 6)
#define OMAPW3G_AUTO_SPI1_SHIFT				6
#define OMAPW3G_AUTO_FSHOSTUSB				(1 << 5)
#define OMAPW3G_AUTO_FSHOSTUSB_SHIFT			5
#define OMAPW3G_AUTO_HSOTGUSB				(1 << 4)
#define OMAPW3G_AUTO_HSOTGUSB_SHIFT			4
#define OMAPW3G_AUTO_UART3				(1 << 3)
#define OMAPW3G_AUTO_UART3_SHIFT			3
#define OMAPW3G_AUTO_UART2				(1 << 2)
#define OMAPW3G_AUTO_UART2_SHIFT			2
#define OMAPW3G_AUTO_UART1				(1 << 1)
#define OMAPW3G_AUTO_UART1_SHIFT			1
#define OMAPW3G_AUTO_MCBSP2				(1 << 0)
#define OMAPW3G_AUTO_MCBSP2_SHIFT			0


/* CM_CLKSEL_CORE */
#define OMAPW3G_CLKSEL_CORE_SHIFT			14
#define OMAPW3G_CLKSEL_CORE_MASK			(0x3 << 14)
#define OMAPW3G_CLKSEL_USIMOCP_DIV_SHIFT		10
#define OMAPW3G_CLKSEL_USIMOCP_DIV_MASK			(0xf << 10)
#define OMAPW3G_CLKSEL_USIMOCP_SRC_SHIFT		8
#define OMAPW3G_CLKSEL_USIMOCP_SRC_MASK			(0x3 << 8)
#define OMAPW3G_CLKSEL_MCBSP2_SHIFT			6
#define OMAPW3G_CLKSEL_MCBSP2_MASK			(0x3 << 6)
#define OMAPW3G_CLKSEL_L4_SHIFT				4
#define OMAPW3G_CLKSEL_L4_MASK				(0x3 << 4)
#define OMAPW3G_CLKSEL_L3_SHIFT				0
#define OMAPW3G_CLKSEL_L3_MASK				(0x3 << 0)

/* CM_CLKSTCTRL_CORE */
#define OMAPW3G_CLKTRCTRL_L4_SHIFT			2
#define OMAPW3G_CLKTRCTRL_L4_MASK			(0x3 << 2)
#define OMAPW3G_CLKTRCTRL_L3_SHIFT			0
#define OMAPW3G_CLKTRCTRL_L3_MASK			(0x3 << 0)

/* CM_CLKSTST_CORE */
#define OMAPW3G_CLKACTIVITY_L4_SHIFT			1
#define OMAPW3G_CLKACTIVITY_L4_MASK			(1 << 1)
#define OMAPW3G_CLKACTIVITY_L3_SHIFT			0
#define OMAPW3G_CLKACTIVITY_L3_MASK			(1 << 0)

/* CM_FCLKEN_WKUP specific bits */
#define OMAPW3G_EN_2GDSM_SYS				(1 << 10)
#define OMAPW3G_EN_2GDSM_SYS_SHIFT			10

/* CM_ICLKEN_WKUP specific bits */
#define OMAPW3G_EN_3GDSM				(1 << 12)
#define OMAPW3G_EN_3GDSM_SHIFT				12
#define OMAPW3G_EN_2GDSM				(1 << 11)
#define OMAPW3G_EN_2GDSM_SHIFT				11
#define OMAPW3G_EN_WDT1					(1 << 4)
#define OMAPW3G_EN_WDT1_SHIFT				4
#define OMAPW3G_EN_SYNCT				(1 << 2)
#define OMAPW3G_EN_SYNCT_SHIFT				2

/* CM_IDLEST_WKUP specific bits */
#define OMAPW3G_ST_3GDSM				(1 << 12)
#define OMAPW3G_ST_3GDSM_SHIFT				12
#define OMAPW3G_ST_WDT2					(1 << 5)
#define OMAPW3G_ST_WDT2_SHIFT				5
#define OMAPW3G_ST_WDT1					(1 << 4)
#define OMAPW3G_ST_WDT1_SHIFT				4
#define OMAPW3G_ST_SYNCT				(1 << 2)
#define OMAPW3G_ST_SYNCT_SHIFT				2

/* CM_AUTOIDLE_WKUP */
#define OMAPW3G_AUTO_3GDSM				(1 << 12)
#define OMAPW3G_AUTO_3GDSM_SHIFT			12
#define OMAPW3G_AUTO_2GDSM				(1 << 11)
#define OMAPW3G_AUTO_2GDSM_SHIFT			11
#define OMAPW3G_AUTO_KBC				(1 << 10)
#define OMAPW3G_AUTO_KBC_SHIFT				10
#define OMAPW3G_AUTO_WDT2				(1 << 5)
#define OMAPW3G_AUTO_WDT2_SHIFT				5
#define OMAPW3G_AUTO_WDT1				(1 << 4)
#define OMAPW3G_AUTO_WDT1_SHIFT				4
#define OMAPW3G_AUTO_GPIO1				(1 << 3)
#define OMAPW3G_AUTO_GPIO1_SHIFT			3
#define OMAPW3G_AUTO_SYNCT				(1 << 2)
#define OMAPW3G_AUTO_SYNCT_SHIFT			2
#define OMAPW3G_AUTO_GPT1				(1 << 0)
#define OMAPW3G_AUTO_GPT1_SHIFT				0

/* CM_CLKSEL_WKUP */
#define OMAPW3G_CLKSEL_GPT1_SHIFT			0
#define OMAPW3G_CLKSEL_GPT1_MASK			(1 << 0)

/* CM_CLKEN_PLL */
#define OMAPW3G_PERIPH_DPLL_DITH_TYPE_SHIFT		31
#define OMAPW3G_PERIPH_DPLL_DITH_TYPE_MASK		(1 << 31)
#define OMAPW3G_PERIPH_DPLL_DITH_SPREAD_SHIFT		29
#define OMAPW3G_PERIPH_DPLL_DITH_SPREAD_MASK		(0x3 << 29)
#define OMAPW3G_PERIPH_DPLL_DITH_FREQ_SHIFT		27
#define OMAPW3G_PERIPH_DPLL_DITH_FREQ_MASK		(0x3 << 27)
#define OMAPW3G_PERIPH_DPLL_DITH_EN_SHIFT		26
#define OMAPW3G_PERIPH_DPLL_DITH_EN_MASK		(1 << 26)
#define OMAPW3G_PERIPH_DPLL_RAMPTIME_SHIFT		24
#define OMAPW3G_PERIPH_DPLL_RAMPTIME_MASK		(0x3 << 24)
#define OMAPW3G_PERIPH_DPLL_FREQSEL_SHIFT		20
#define OMAPW3G_PERIPH_DPLL_FREQSEL_MASK		(0xf << 20)
#define OMAPW3G_EN_PERIPH_DPLL_DRIFTGUARD_SHIFT		19
#define OMAPW3G_EN_PERIPH_DPLL_DRIFTGUARD_MASK		(1 << 19)
#define OMAPW3G_EN_PERIPH_DPLL_SHIFT			16
#define OMAPW3G_EN_PERIPH_DPLL_MASK			(0x7 << 16)
#define OMAPW3G_CORE_DPLL_DITH_TYPE_SHIFT		15
#define OMAPW3G_CORE_DPLL_DITH_TYPE_MASK		(1 << 15)
#define OMAPW3G_CORE_DPLL_DITH_SPREAD_SHIFT		13
#define OMAPW3G_CORE_DPLL_DITH_SPREAD_MASK		(0x3 << 13)
#define OMAPW3G_CORE_DPLL_DITH_FREQ_SHIFT		11
#define OMAPW3G_CORE_DPLL_DITH_FREQ_MASK		(0x3 << 11)
#define OMAPW3G_CORE_DPLL_DITH_EN_SHIFT			10
#define OMAPW3G_CORE_DPLL_DITH_EN_MASK			(1 << 10)
#define OMAPW3G_CORE_DPLL_RAMPTIME_SHIFT		8
#define OMAPW3G_CORE_DPLL_RAMPTIME_MASK			(0x3 << 8)
#define OMAPW3G_CORE_DPLL_FREQSEL_SHIFT			4
#define OMAPW3G_CORE_DPLL_FREQSEL_MASK			(0xf << 4)
#define OMAPW3G_EN_CORE_DPLL_DRIFTGUARD_SHIFT		3
#define OMAPW3G_EN_CORE_DPLL_DRIFTGUARD_MASK		(1 << 3)
#define OMAPW3G_EN_CORE_DPLL_SHIFT			0
#define OMAPW3G_EN_CORE_DPLL_MASK			(0x7 << 0)

/* CM_IDLEST_CKGEN */
#define OMAPW3G_ST_PER_DITH_ACK				(1 << 9)
#define OMAPW3G_ST_CORE_DITH_ACK			(1 << 8)
#define OMAPW3G_ST_13M_CLK				(1 << 6)
#define OMAPW3G_ST_60M_CLK				(1 << 5)
#define OMAPW3G_ST_96M_CLK				(1 << 2)
#define OMAPW3G_ST_PERIPH_CLK_SHIFT			1
#define OMAPW3G_ST_PERIPH_CLK_MASK			(1 << 1)
#define OMAPW3G_ST_CORE_CLK_SHIFT			0
#define OMAPW3G_ST_CORE_CLK_MASK			(1 << 0)

/* CM_AUTOIDLE_PLL */
#define OMAPW3G_AUTO_PERIPH_DPLL_SHIFT			3
#define OMAPW3G_AUTO_PERIPH_DPLL_MASK			(0x7 << 3)
#define OMAPW3G_AUTO_CORE_DPLL_SHIFT			0
#define OMAPW3G_AUTO_CORE_DPLL_MASK			(0x7 << 0)

/* CM_CLKSEL1_PLL */
#define OMAPW3G_CORE_DPLL_CLKOUT_DIV_SHIFT		27
#define OMAPW3G_CORE_DPLL_CLKOUT_DIV_MASK		(0x1f << 27)
#define OMAPW3G_CORE_DPLL_MULT_SHIFT			16
#define OMAPW3G_CORE_DPLL_MULT_MASK			(0x7ff << 16)
#define OMAPW3G_CORE_DPLL_DIV_SHIFT			8
#define OMAPW3G_CORE_DPLL_DIV_MASK			(0x7f << 8)

/* CM_CLKSEL2_PLL */
#define OMAPW3G_PERIPH_DPLL_MULT_SHIFT			8
#define OMAPW3G_PERIPH_DPLL_MULT_MASK			(0x7ff << 8)
#define OMAPW3G_PERIPH_DPLL_DIV_SHIFT			0
#define OMAPW3G_PERIPH_DPLL_DIV_MASK			(0x7f << 0)

/* CM_CLKSEL3_PLL */
#define OMAPW3G_DIV_60M_SHIFT				8
#define OMAPW3G_DIV_60M_MASK				(0x1f << 8)
#define OMAPW3G_DIV_96M_SHIFT				0
#define OMAPW3G_DIV_96M_MASK				(0x1f << 0)

/* CM_CLKOUT_CTRL */
#define OMAPW3G_CLKOUT2_EN_SHIFT			7
#define OMAPW3G_CLKOUT2_EN				(1 << 7)
#define OMAPW3G_CLKOUT2_POL_SHIFT			6
#define OMAPW3G_CLKOUT2_POL				(1 << 6)
#define OMAPW3G_CLKOUT2_DIV_SHIFT			3
#define OMAPW3G_CLKOUT2_DIV_MASK			(0x7 << 3)
#define OMAPW3G_CLKOUT2SOURCE_SHIFT			0
#define OMAPW3G_CLKOUT2SOURCE_MASK			(0x7 << 0)

/* CM_FCLKEN_DSS */
#define OMAPW3G_EN_DSS2				(1 << 1)
#define OMAPW3G_EN_DSS2_SHIFT				1
#define OMAPW3G_EN_DSS1				(1 << 0)
#define OMAPW3G_EN_DSS1_SHIFT				0

/* CM_ICLKEN_DSS */
#define OMAPW3G_CM_ICLKEN_DSS_EN_DSS			(1 << 0)
#define OMAPW3G_CM_ICLKEN_DSS_EN_DSS_SHIFT		0

/* CM_IDLEST_DSS */
#define OMAPW3G_ST_DSS_IDLE_SHIFT			1
#define OMAPW3G_ST_DSS_IDLE_MASK			(1 << 1)
#define OMAPW3G_ST_DSS_STDBY_SHIFT			0
#define OMAPW3G_ST_DSS_STDBY_MASK			(1 << 0)

/* CM_AUTOIDLE_DSS */
#define OMAPW3G_AUTO_DSS				(1 << 0)
#define OMAPW3G_AUTO_DSS_SHIFT				0

/* CM_CLKSEL_DSS */
#define OMAPW3G_CLKSEL_DSS1_SHIFT			0
#define OMAPW3G_CLKSEL_DSS1_MASK			(0x1f << 0)

/* CM_SLEEPDEP_DSS specific bits */

/* CM_CLKSTCTRL_DSS */
#define OMAPW3G_CLKTRCTRL_DSS_SHIFT			0
#define OMAPW3G_CLKTRCTRL_DSS_MASK			(0x3 << 0)

/* CM_CLKSTST_DSS */
#define OMAPW3G_CLKACTIVITY_DSS_SHIFT			0
#define OMAPW3G_CLKACTIVITY_DSS_MASK			(1 << 0)

/* CM_FCLKEN_CAM and CM_ICLKEN_CAM specific bits */
#define OMAPW3G_EN_CAM					(1 << 0)
#define OMAPW3G_EN_CAM_SHIFT				0


/* CM_IDLEST_CAM */
#define OMAPW3G_ST_CAM_IDLE				(1 << 1)
#define OMAPW3G_ST_CAM_STBY				(1 << 0)

/* CM_AUTOIDLE_CAM */
#define OMAPW3G_AUTO_CAM				(1 << 0)
#define OMAPW3G_AUTO_CAM_SHIFT				0

/* CM_CLKSEL_CAM */
#define OMAPW3G_CLKSEL_CAM_SHIFT			0
#define OMAPW3G_CLKSEL_CAM_MASK				(0x1f << 0)

/* CM_SLEEPDEP_CAM specific bits */
#define OMAPW3G_CAM_EN_DSP_SHIFT			5
#define OMAPW3G_CAM_EN_DSP_MASK				(1 << 5)
#define OMAPW3G_CAM_EN_MPU_SHIFT			4
#define OMAPW3G_CAM_EN_MPU_MASK				(1 << 4)

/* CM_CLKSTCTRL_CAM */
#define OMAPW3G_CLKTRCTRL_CAM_SHIFT			0
#define OMAPW3G_CLKTRCTRL_CAM_MASK			(0x3 << 0)

/* CM_CLKSTST_CAM */
#define OMAPW3G_CLKACTIVITY_CAM_SHIFT			0
#define OMAPW3G_CLKACTIVITY_CAM_MASK			(1 << 0)

/* CM_FCLKEN_APP and CM_ICLKEN_APP shared bits */
#define OMAPW3G_EN_HDQ					(1 << 2)
#define OMAPW3G_EN_HDQ_SHIFT				2
#define OMAPW3G_EN_SPI2					(1 << 1)
#define OMAPW3G_EN_SPI2_SHIFT				1
#define OMAPW3G_EN_GPT3					(1 << 0)
#define OMAPW3G_EN_GPT3_SHIFT				0

/* CM_ICLKEN_APP specific bits */
#define OMAPW3G_EN_SHA2					(1 << 8)
#define OMAPW3G_EN_SHA2_SHIFT				8
#define OMAPW3G_EN_RNG					(1 << 7)
#define OMAPW3G_EN_RNG_SHIFT				7
#define OMAPW3G_EN_PKA					(1 << 6)
#define OMAPW3G_EN_PKA_SHIFT				6
#define OMAPW3G_EN_DES3					(1 << 5)
#define OMAPW3G_EN_DES3_SHIFT				5
#define OMAPW3G_EN_AES					(1 << 4)
#define OMAPW3G_EN_AES_SHIFT				4
#define OMAPW3G_EN_IPC					(1 << 3)
#define OMAPW3G_EN_IPC_SHIFT				3


/* CM_IDLEST_APP specific bits */
#define OMAPW3G_ST_SHA2					(1 << 8)
#define OMAPW3G_ST_SHA2_SHIFT				8
#define OMAPW3G_ST_RNG					(1 << 7)
#define OMAPW3G_ST_RNG_SHIFT				7
#define OMAPW3G_ST_PKA					(1 << 6)
#define OMAPW3G_ST_PKA_SHIFT				6
#define OMAPW3G_ST_DES3					(1 << 5)
#define OMAPW3G_ST_DES3_SHIFT				5
#define OMAPW3G_ST_AES					(1 << 4)
#define OMAPW3G_ST_AES_SHIFT				4
#define OMAPW3G_ST_IPC					(1 << 3)
#define OMAPW3G_ST_IPC_SHIFT				3
#define OMAPW3G_ST_HDQ					(1 << 2)
#define OMAPW3G_ST_HDQ_SHIFT				2
#define OMAPW3G_ST_SPI2					(1 << 1)
#define OMAPW3G_ST_SPI2_SHIFT				1
#define OMAPW3G_ST_GPT3					(1 << 0)
#define OMAPW3G_ST_GPT3_SHIFT				0

/* CM_AUTOIDLE_APP specific bits */
#define OMAPW3G_AUTO_SHA2				(1 << 8)
#define OMAPW3G_AUTO_SHA2_SHIFT				8
#define OMAPW3G_AUTO_RNG				(1 << 7)
#define OMAPW3G_AUTO_RNG_SHIFT				7
#define OMAPW3G_AUTO_PKA				(1 << 6)
#define OMAPW3G_AUTO_PKA_SHIFT				6
#define OMAPW3G_AUTO_DES3				(1 << 5)
#define OMAPW3G_AUTO_DES3_SHIFT				5
#define OMAPW3G_AUTO_AES				(1 << 4)
#define OMAPW3G_AUTO_AES_SHIFT				4
#define OMAPW3G_AUTO_IPC				(1 << 3)
#define OMAPW3G_AUTO_IPC_SHIFT				3
#define OMAPW3G_AUTO_HDQ				(1 << 2)
#define OMAPW3G_AUTO_HDQ_SHIFT				2
#define OMAPW3G_AUTO_SPI2				(1 << 1)
#define OMAPW3G_AUTO_SPI2_SHIFT				1
#define OMAPW3G_AUTO_GPT3				(1 << 0)
#define OMAPW3G_AUTO_GPT3_SHIFT				0

/* CM_CLKSTCTRL_APP specific bits */
#define OMAPW3G_CLKTRCTRL_APP_L4_SHIFT            2
#define OMAPW3G_CLKTRCTRL_APP_L4_MASK             (0x3 << 2)
#define OMAPW3G_CLKTRCTRL_APP_L3_SHIFT            0
#define OMAPW3G_CLKTRCTRL_APP_L3_MASK             (0x3 << 0)

/* CM_CLKSEL_APP specific bits */
#define OMAPW3G_CLKSEL_GPT3_MASK			(1 << 0)

/* CM_CLKSEL1_EMU */
#define OMAPW3G_DIV_DPLL4_SHIFT				24
#define OMAPW3G_DIV_DPLL4_MASK				(0x1f << 24)
#define OMAPW3G_DIV_DPLL3_SHIFT				16
#define OMAPW3G_DIV_DPLL3_DPLL_MASK			(0x1f << 16)
#define OMAPW3G_CLKSEL_STM_DIV_SHIFT			12
#define OMAPW3G_CLKSEL_STM_DIV_MASK			(0xf << 12)
#define OMAPW3G_CLKSEL_TRACE_DIV_SHIFT			8
#define OMAPW3G_CLKSEL_TRACE_DIV_MASK			(0xf << 8)
#define OMAPW3G_CLKSEL_DPLL1_SRC_SHIFT			7
#define OMAPW3G_CLKSEL_DPLL1_SRC_MASK			(1 << 7)
#define OMAPW3G_CLKSEL_STM_SRC_SHIFT			3
#define OMAPW3G_CLKSEL_STM_SRC_MASK			(0x3 << 3)
#define OMAPW3G_CLKSEL_TRACE_SRC_SHIFT			1
#define OMAPW3G_CLKSEL_TRACE_SRC_MASK			(0x3 << 1)

/* CM_CLKSTCTRL_EMU */
#define OMAPW3G_CLKTRCTRL_EMU_SHIFT			0
#define OMAPW3G_CLKTRCTRL_EMU_MASK			(0x3 << 0)

/* CM_CLKSTST_EMU */
#define OMAPW3G_CLKACTIVITY_EMU_SHIFT			0
#define OMAPW3G_CLKACTIVITY_EMU_MASK			(1 << 0)

/* CM_CLKSEL2_EMU specific bits */
#define OMAPW3G_CORE_DPLL_EMU_MULT_SHIFT		8
#define OMAPW3G_CORE_DPLL_EMU_MULT_MASK			(0x7ff << 8)
#define OMAPW3G_CORE_DPLL_EMU_DIV_SHIFT			0
#define OMAPW3G_CORE_DPLL_EMU_DIV_MASK			(0x7f << 0)

/* CM_FCLKEN_AUD and CM_ICLKEN_AUD shared bits */
#define OMAPW3G_EN_MCBSP1				(1 << 3)
#define OMAPW3G_EN_MCBSP1_SHIFT				3
#define OMAPW3G_EN_GPT2					(1 << 2)
#define OMAPW3G_EN_GPT2_SHIFT				2
#define OMAPW3G_EN_GPIO3				(1 << 1)
#define OMAPW3G_EN_GPIO3_SHIFT				1
#define OMAPW3G_EN_GPIO2				(1 << 0)
#define OMAPW3G_EN_GPIO2_SHIFT				0

/* CM_IDLEST_AUD specific bits */
#define OMAPW3G_ST_MCBSP1				(1 << 3)
#define OMAPW3G_ST_MCBSP1_SHIFT				3
#define OMAPW3G_ST_GPT2					(1 << 2)
#define OMAPW3G_ST_GPT2_SHIFT				2
#define OMAPW3G_ST_GPIO3				(1 << 1)
#define OMAPW3G_ST_GPIO3_SHIFT				1
#define OMAPW3G_ST_GPIO2				(1 << 0)
#define OMAPW3G_ST_GPIO2_SHIFT				0

/* CM_AUTOIDLE_AUD specific bits */
#define OMAPW3G_AUTO_MCBSP1				(1 << 3)
#define OMAPW3G_AUTO_MCBSP1_SHIFT			3
#define OMAPW3G_AUTO_GPT2				(1 << 2)
#define OMAPW3G_AUTO_GPT2_SHIFT				2
#define OMAPW3G_AUTO_GPIO3				(1 << 1)
#define OMAPW3G_AUTO_GPIO3_SHIFT				1
#define OMAPW3G_AUTO_GPIO2				(1 << 0)
#define OMAPW3G_AUTO_GPIO2_SHIFT				0

/* CM_CLKSTCTRL_AUD specific bits */
#define OMAPW3G_CLKTRCTRL_AUD_SHIFT            0
#define OMAPW3G_CLKTRCTRL_AUD_MASK             (0x3 << 0)

/* CM_CLKSEL_AUD specific bits */
#define OMAPW3G_CLKSEL_MCBSP1_SHIFT			1
#define OMAPW3G_CLKSEL_MCBSP1_MASK			(0x3 << 1)
#define OMAPW3G_CLKSEL_MCBSP1_CLKS			(0x0 << 1)
#define OMAPW3G_CLKSEL_MCBSP1_SYS_CLK			(0x1 << 1)
#define OMAPW3G_CLKSEL_MCBSP1_96M			(0x2 << 1)
#define OMAPW3G_CLKSEL_MCBSP1_MDM_15M			(0x3 << 1)
#define OMAPW3G_CLKSEL_GPT2_MASK			(1 << 0)



#endif
